export const PRODUCTS = [
  {
    id: 1,
    title: "سانتافه 2015",
    category: "Hyundai",
    price: 3650000000,
    imgSrc: [
      "/images/foreigner/Hyundai/santa-fe-2015-1.jpg",
      "/images/foreigner/Hyundai/santa-fe-2015-2.jpg",
      "/images/foreigner/Hyundai/santa-fe-2015-3.jpg"
    ],
    mileage: 200000,
    model: 2015,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "یکی از محبوب‌ترین شاسی‌بلندهای بازار ایران با هندلینگ عالی. خودرو کاملاً خانگی، فول آپشن با مانیتور بزرگ و سقف پانوراما، تمامی سرویس‌های دوره‌ای در نمایندگی مجاز انجام شده و آماده سفر است.",
    hasGuarantee: "yes",
  },
  {
    id: 2,
    title: "پژو 206",
    category: "Peugeot",
    price: 725000000,
    imgSrc: [
      "/images/internal/Peugeot/peugeot-206-1.jpg",
      "/images/internal/Peugeot/peugeot-206-2.jpg",
      "/images/internal/Peugeot/peugeot-206-3.jpg"
    ],
    mileage: 105000,
    model: 1398,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "رنگ دار",
    descriptiion: "ماشین بسیار خوش‌رکاب و کم‌مصرف، مناسب برای ترددهای داخل شهر. دارای روکش صندلی چرمی نو، ضبط تصویری و سنسور دنده عقب. از لحاظ فنی کاملاً بی‌نقص و شتاب بسیار خوبی دارد.",
    hasGuarantee: "no",
  },
  {
    id: 3,
    title: "تویوتا کمری 2016",
    category: "Toyota",
    price: 4200000000,
    imgSrc: [
      "/images/foreigner/Toyota/camry-2016-1.jpg",
      "/images/foreigner/Toyota/camry-2016-2.jpg",
      "/images/foreigner/Toyota/camry-2016-3.jpg"
    ],
    mileage: 150000,
    model: 2016,
    gearbox: "اتوماتیک",
    color: "مشکی",
    bodyStatus: "بی رنگ",
    descriptiion: "نماد استهلاک پایین و کیفیت ساخت ژاپنی. سواری فوق‌العاده نرم و کابین بی‌صدا، بدنه بدون خط و خش و مشابه صفر. این خودرو مخصوص کسانی است که به دنبال اصالت و دوام قطعات هستند.",
    hasGuarantee: "yes",
  },
  {
    id: 4,
    title: "بی ام و 528",
    category: "Bmw",
    price: 6800000000,
    imgSrc: [
      "/images/foreigner/Bmw/bmw-528-1.jpg",
      "/images/foreigner/Bmw/bmw-528-2.jpg",
      "/images/foreigner/Bmw/bmw-528-3.jpg"
    ],
    mileage: 120000,
    model: 2014,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "فول آپشن‌ترین نسخه موجود (ابودبی)، دارای ۵ کلید و کیت M فابریک. شتاب خیره‌کننده در کنار سیستم صوتی هارمن کاردن و صندلی‌های راحت Comfort. خودرو با وسواس زیاد نگهداری شده و کاملاً بی رنگ است.",
    hasGuarantee: "yes",
  },
  {
    id: 5,
    title: "مرسدس C200",
    category: "Mercedes Benz",
    price: 7200000000,
    imgSrc: [
      "/images/foreigner/MercedesBenz/benz-c200-1.jpg",
      "/images/foreigner/MercedesBenz/benz-c200-2.jpg",
      "/images/foreigner/MercedesBenz/benz-c200-3.jpg"
    ],
    mileage: 98000,
    model: 2015,
    gearbox: "اتوماتیک",
    color: "مشکی",
    bodyStatus: "بی رنگ",
    descriptiion: "تجربه رانندگی با شکوه آلمانی. خودروی کم‌کارکرد با طراحی داخلی مدرن و متریال درجه یک. مجهز به رادارهای ایمنی، سیستم پارک خودکار و سقف پانوراما. بدنه سرامیک شده و در وضعیت عالی قرار دارد.",
    hasGuarantee: "yes",
  },
  {
    id: 6,
    title: "پژو پارس",
    category: "Peugeot",
    price: 650000000,
    imgSrc: [
      "/images/internal/Peugeot/peugeot-pars-1.jpg",
      "/images/internal/Peugeot/peugeot-pars-2.jpg",
      "/images/internal/Peugeot/peugeot-pars-3.jpg"
    ],
    mileage: 130000,
    model: 1397,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "رنگ دار",
    descriptiion: "پژو پارس سال، موتور تقویت شده و بسیار پرشتاب. دیسک و صفحه به تازگی تعویض شده و کولر روشن. با وجود چند لکه رنگ، شاسی‌ها کاملاً سالم هستند و برای مصرف‌کننده گزینه‌ای بسیار اقتصادی است.",
    hasGuarantee: "no",
  },
  {
    id: 7,
    title: "ساینا S",
    category: "Saipa",
    price: 420000000,
    imgSrc: [
      "/images/internal/Saipa/saina-s-1.jpg",
      "/images/internal/Saipa/saina-s-2.jpg",
      "/images/internal/Saipa/saina-s-3.jpg"
    ],
    mileage: 40000,
    model: 1401,
    gearbox: "دنده دستی",
    color: "آبی",
    bodyStatus: "بی رنگ",
    descriptiion: "نسخه جدید ساینا S با ظاهر مدرن‌تر و فرمان دی‌کات. کارکرد بسیار پایین، زاپاس زیرش نرفته و دارای گارانتی فعال سایپا. رنگ آبی متالیک خاص که در خیابان حسابی جلب توجه می‌کند.",
    hasGuarantee: "yes",
  },
  {
    id: 8,
    title: "هیوندای النترا",
    category: "Hyundai",
    price: 3100000000,
    imgSrc: [
      "/images/foreigner/Hyundai/elantra-1.jpg",
      "/images/foreigner/Hyundai/elantra-2.jpg",
      "/images/foreigner/Hyundai/elantra-3.jpg"
    ],
    mileage: 90000,
    model: 2017,
    gearbox: "اتوماتیک",
    color: "مشکی",
    bodyStatus: "بی رنگ",
    descriptiion: "النترا مدل AD با طراحی آیرودینامیک و جذاب. دارای گرم‌کن و سرد‌کن صندلی، سیستم ورود بدون کلید و مصرف سوخت بسیار بهینه. خودروی دوم بوده و بیشتر در پارکینگ مسقف نگهداری شده است.",
    hasGuarantee: "yes",
  },
  {
    id: 9,
    title: "تویوتا راو4",
    category: "Toyota",
    price: 5600000000,
    imgSrc: [
      "/images/foreigner/Toyota/rav4-1.jpg",
      "/images/foreigner/Toyota/rav4-2.jpg",
      "/images/foreigner/Toyota/rav4-3.jpg"
    ],
    mileage: 110000,
    model: 2018,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "قدرتمندترین شاسی‌بلند شهری تویوتا با قابلیت دو دیفرانسیل (AWD). بسیار جادار برای خانواده، مناسب برای سفرهای جاده‌ای و آفرود سبک. از لحاظ فنی کاملاً پلمپ و دارای تاییدیه کارشناسی.",
    hasGuarantee: "yes",
  },
  {
    id: 10,
    title: "پراید 131",
    category: "Saipa",
    price: 260000000,
    imgSrc: [
      "/images/internal/Saipa/pride-131-1.jpg",
      "/images/internal/Saipa/pride-131-2.jpg",
      "/images/internal/Saipa/pride-131-3.jpg"
    ],
    mileage: 170000,
    model: 1395,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "رنگ دار",
    descriptiion: "ماشین اقتصادی و کم‌خرج، موتور و گیربکس به شرط مکانیک شما. بیمه شخص ثالث ۱۰ ماه دارد و لاستیک‌ها ۸۰ درصد هستند. انتخابی عالی برای شروع رانندگی یا کار در اسنپ.",
    hasGuarantee: "no",
  },
  {
    id: 11,
    title: "بی ام و X3",
    category: "Bmw",
    price: 8900000000,
    imgSrc: [
      "/images/foreigner/Bmw/bmw-x3-1.jpg",
      "/images/foreigner/Bmw/bmw-x3-2.jpg",
      "/images/foreigner/Bmw/bmw-x3-3.jpg"
    ],
    mileage: 80000,
    model: 2018,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "لوکس‌ترین کراس‌اوور میان‌رده با تکنولوژی xDrive. بدنه سرامیک ۵ ساله شده، مجهز به دوربین ۳۶۰ درجه و سیستم هوشمند کمکی راننده. خودرو مشابه صفر و بدون کوچکترین خط و خش روی رینگ‌ها.",
    hasGuarantee: "yes",
  },
  {
    id: 12,
    title: "پژو 207",
    category: "Peugeot",
    price: 920000000,
    imgSrc: [
      "/images/internal/Peugeot/peugeot-207-1.jpg",
      "/images/internal/Peugeot/peugeot-207-2.jpg",
      "/images/internal/Peugeot/peugeot-207-3.jpg"
    ],
    mileage: 60000,
    model: 1400,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "رنگ قرمز دوپوششه سفارشی، بسیار تمیز و جوان‌پسند. دارای فرمان برقی، کروز کنترل و مانیتور لمسی فابریک. تمام قطعات مصرفی از جمله لنت و روغن به تازگی با برندهای اصلی تعویض شده‌اند.",
    hasGuarantee: "yes",
  },
  {
    id: 13,
    title: "مرسدس E350",
    category: "Mercedes Benz",
    price: 9500000000,
    imgSrc: [
      "/images/foreigner/MercedesBenz/benz-e350-1.jpg",
      "/images/foreigner/MercedesBenz/benz-e350-2.jpg",
      "/images/foreigner/MercedesBenz/benz-e350-3.jpg"
    ],
    mileage: 140000,
    model: 2014,
    gearbox: "اتوماتیک",
    color: "نقره ای",
    bodyStatus: "بی رنگ",
    descriptiion: "کشتی لوکس آلمانی با پیشرانه قدرتمند ۶ سیلندر. کابین با تریم چوب و چرم طبیعی، صندلی‌ها دارای ماساژور و حافظه یکپارچه. خودرو از نظر فنی در وضعیت ایده‌آل و تمام آپشن‌ها فعال هستند.",
    hasGuarantee: "yes",
  },
  {
    id: 14,
    title: "تیبا 2",
    category: "Saipa",
    price: 390000000,
    imgSrc: [
      "/images/internal/Saipa/tiba2-1.jpg",
      "/images/internal/Saipa/tiba2-2.jpg",
      "/images/internal/Saipa/tiba2-3.jpg"
    ],
    mileage: 75000,
    model: 1399,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "هاچ‌بک اقتصادی با هزینه‌های نگهداری بسیار پایین. ماشین بدون رنگ و تصادف، فنی سالم و زیرپا عالی. شیشه‌های عقب برقی و آینه‌ها برقی شده‌اند و دارای دزدگیر تصویری می‌باشد.",
    hasGuarantee: "no",
  },
  {
    id: 15,
    title: "هیوندای توسان",
    category: "Hyundai",
    price: 5400000000,
    imgSrc: [
      "/images/foreigner/Hyundai/tucson-1.jpg",
      "/images/foreigner/Hyundai/tucson-2.jpg",
      "/images/foreigner/Hyundai/tucson-3.jpg"
    ],
    mileage: 130000,
    model: 2017,
    gearbox: "اتوماتیک",
    color: "مشکی",
    bodyStatus: "بی رنگ",
    descriptiion: "شاسی‌بلند محبوب با سواری نرم و فضای کابین عالی. فول آپشن دو دیفرانسیل، دارای اتوهلد، ترمز پارک برقی و سقف پانوراما. لاستیک‌ها ۱۰۰ درصد نو و مناسب برای خانواده‌های پرجمعیت.",
    hasGuarantee: "yes",
  },
  {
    id: 16,
    title: "دنا پلاس",
    category: "Peugeot",
    price: 830000000,
    imgSrc: [
      "/images/internal/Peugeot/dena-plus-1.jpg",
      "/images/internal/Peugeot/dena-plus-2.jpg",
      "/images/internal/Peugeot/dena-plus-3.jpg"
    ],
    mileage: 50000,
    model: 1400,
    gearbox: "دنده دستی",
    color: "نوک مدادی",
    bodyStatus: "بی رنگ",
    descriptiion: "دنا پلاس تیپ ۲ فول، دارای سانروف و صندلی‌های برقی ۸ حالته. بدنه بدون خط و خش و آینه، کابین بوی نو بودن می‌دهد. آپدیت‌های نرم‌افزاری موتور انجام شده و شتاب فوق‌العاده‌ای دارد.",
    hasGuarantee: "yes",
  },
  {
    id: 17,
    title: "سراتو ",
    category: "Saipa",
    price: 4100000000,
    imgSrc: [
      "/images/internal/Saipa/cerato-1.jpg",
      "/images/internal/Saipa/cerato-2.jpg",
      "/images/internal/Saipa/cerato-3.jpg"
    ],
    mileage: 100000,
    model: 2016,
    gearbox: "اتوماتیک",
    color: "نقره ای",
    bodyStatus: "بی رنگ",
    descriptiion: "سراتو ۲۰۰۰ آپشنال مونتاژ سایپا، موتور و گیربکس کاملاً کره‌ای. مجهز به پدال شیفتر پشت فرمان، کی‌لس استارتر و مانیتور اندروید. خودرو بسیار پرشتاب و در عین حال نرم و پایدار در جاده.",
    hasGuarantee: "yes",
  },
  {
    id: 18,
    title: "لیفان X60",
    category: "Saipa",
    price: 980000000,
    imgSrc: [
      "/images/internal/Saipa/lifan-x60-1.jpg",
      "/images/internal/Saipa/lifan-x60-2.jpg",
      "/images/internal/Saipa/lifan-x60-3.jpg"
    ],
    mileage: 140000,
    model: 1396,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "رنگ دار",
    descriptiion: "کراس‌اوور جادار با قیمت مناسب. دیسک و صفحه و کلاچ به تازگی سرویس شده و بسیار نرم عمل می‌کند. دارای مانیتور لمسی، دوربین دنده عقب و گارد جلو و عقب جهت زیبایی و امنیت بیشتر.",
    hasGuarantee: "no",
  },
  {
    id: 19,
    title: "تویوتا کرولا",
    category: "Toyota",
    price: 3500000000,
    imgSrc: [
      "/images/foreigner/Toyota/corolla-1.jpg",
      "/images/foreigner/Toyota/corolla-2.jpg",
      "/images/foreigner/Toyota/corolla-3.jpg"
    ],
    mileage: 90000,
    model: 2015,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "معروف به ماشین بی‌مرگ تویوتا. کارکرد واقعی به شرط دیاگ، کابین بسیار تمیز و بدون کوچکترین صدا. اگر به دنبال ماشینی هستید که سال‌ها بدون هزینه فقط بنزین بزنید و برانید، بهترین انتخاب است.",
    hasGuarantee: "yes",
  },
  {
    id: 20,
    title: "بی ام و 320",
    category: "Bmw",
    price: 7600000000,
    imgSrc: [
      "/images/foreigner/Bmw/bmw-320-1.jpg",
      "/images/foreigner/Bmw/bmw-320-2.jpg",
      "/images/foreigner/Bmw/bmw-320-3.jpg"
    ],
    mileage: 110000,
    model: 2016,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "سدان اسپرت با هندلینگ بی‌رقیب. خودرو دارای کیت بدنه M، رینگ‌های ۱۸ اینچی و شیفتر پشت فرمان است. سیستم تعلیق کاملاً چک شده و رانندگی هیجان‌انگیزی را در حالت Sport+ ارائه می‌دهد.",
    hasGuarantee: "yes",
  },
  {
    id: 21,
    title: "پراید 111",
    category: "Saipa",
    price: 240000000,
    imgSrc: [
      "/images/internal/Saipa/pride-111-1.jpg",
      "/images/internal/Saipa/pride-111-2.jpg",
      "/images/internal/Saipa/pride-111-3.jpg"
    ],
    mileage: 180000,
    model: 1394,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "رنگ دار",
    descriptiion: "هاچ‌بک جوان‌پسند و تند و تیز. سیستم صوتی خوب، روکش صندلی نو و کف‌پایی سه بعدی دارد. جلوبندی و کمک‌فنرها به تازگی تعویض شده‌اند و آماده تعویض پلاک است.",
    hasGuarantee: "no",
  },
  {
    id: 22,
    title: "پژو 405",
    category: "Peugeot",
    price: 500000000,
    imgSrc: [
      "/images/internal/Peugeot/peugeot-405-1.jpg",
      "/images/internal/Peugeot/peugeot-405-2.jpg",
      "/images/internal/Peugeot/peugeot-405-3.jpg"
    ],
    mileage: 160000,
    model: 1393,
    gearbox: "دنده دستی",
    color: "نوک مدادی",
    bodyStatus: "رنگ دار",
    descriptiion: "خودرویی با اصالت و جادار، مناسب برای جاده. واشر سرسیلندر به تازگی با بهترین برند بازار تعویض شده و مشکل گرم‌ کردن ندارد. موتور کاملاً سرحال و کابین بدون صدای اضافه.",
    hasGuarantee: "no",
  },
  {
    id: 23,
    title: "هیوندای آزرا",
    category: "Hyundai",
    price: 4700000000,
    imgSrc: [
      "/images/foreigner/Hyundai/azera-1.jpg",
      "/images/foreigner/Hyundai/azera-2.jpg",
      "/images/foreigner/Hyundai/azera-3.jpg"
    ],
    mileage: 125000,
    model: 2013,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "آزرا گرانجور با موتور ۶ سیلندر پرقدرت. نهایت نرمی و راحتی در رانندگی طولانی مدت. فول آپشن شامل پرده برقی عقب، گرم‌کن تمام صندلی‌ها و سیستم صوتی اینفینیتی با ساب‌ووفر فابریک.",
    hasGuarantee: "yes",
  },
  {
    id: 24,
    title: "مرسدس CLA",
    category: "Mercedes Benz",
    price: 8800000000,
    imgSrc: [
      "/images/foreigner/MercedesBenz/benz-cla-1.jpg",
      "/images/foreigner/MercedesBenz/benz-cla-2.jpg",
      "/images/foreigner/MercedesBenz/benz-cla-3.jpg"
    ],
    mileage: 95000,
    model: 2017,
    gearbox: "اتوماتیک",
    color: "مشکی",
    bodyStatus: "بی رنگ",
    descriptiion: "طراحی کوپه ۴ درب بسیار خاص و چشم‌نواز. رنگ قرمز آتشین بدون حتی یک لکه رنگ یا قری. کابین با نورپردازی داینامیک و صندلی‌های باکت اسپرت که حس بی‌نظیری به راننده منتقل می‌کند.",
    hasGuarantee: "yes",
  },
  {
    id: 25,
    title: "کوییک R",
    category: "Saipa",
    price: 460000000,
    imgSrc: [
      "/images/internal/Saipa/quick-r-1.jpg",
      "/images/internal/Saipa/quick-r-2.jpg",
      "/images/internal/Saipa/quick-r-3.jpg"
    ],
    mileage: 30000,
    model: 1402,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "کوییک دو رنگ (R) مدل ۱۴۰۲، مشابه خشک. کارکرد واقعی بسیار کم، دارای سنسور دنده عقب و رینگ آلومینیومی فابریک. هنوز بوی نویی کارخانه داخل کابین حس می‌شود و آماده انتقال سند است.",
    hasGuarantee: "yes",
  },
  {
    id: 26,
    title: "تویوتا لندکروز",
    category: "Toyota",
    price: 15000000000,
    imgSrc: [
      "/images/foreigner/Toyota/landcruiser-1.jpg",
      "/images/foreigner/Toyota/landcruiser-2.jpg",
      "/images/foreigner/Toyota/landcruiser-3.jpg"
    ],
    mileage: 180000,
    model: 2012,
    gearbox: "اتوماتیک",
    color: "مشکی",
    bodyStatus: "بی رنگ",
    descriptiion: "فرمانده جاده‌ها و بیراهه‌ها. لندکروز GXR با موتور قدرتمند، کیت فیس‌لیفت ۲۰۱۸ نصب شده با بهترین قطعات. وضعیت شاسی و بدنه فوق‌العاده سالم و آماده برای آفرودهای سنگین و لوکس‌سواری.",
    hasGuarantee: "yes",
  },
  {
    id: 27,
    title: "بی ام و X1",
    category: "Bmw",
    price: 6900000000,
    imgSrc: [
      "/images/foreigner/Bmw/bmw-x1-1.jpg",
      "/images/foreigner/Bmw/bmw-x1-2.jpg",
      "/images/foreigner/Bmw/bmw-x1-3.jpg"
    ],
    mileage: 100000,
    model: 2017,
    gearbox: "اتوماتیک",
    color: "مشکی",
    bodyStatus: "بی رنگ",
    descriptiion: "کراس‌اوور چابک و هوشمند بی ام و. موتور توئین پاور توربو با مصرف سوخت بسیار پایین و شتاب عالی. تمام سرویس‌ها در نمایندگی پرشیا خودرو انجام شده و دارای کیت بدنه M Sport است.",
    hasGuarantee: "yes",
  },
  {
    id: 28,
    title: "پژو 2008",
    category: "Peugeot",
    price: 1800000000,
    imgSrc: [
      "/images/internal/Peugeot/peugeot-2008-1.jpg",
      "/images/internal/Peugeot/peugeot-2008-2.jpg",
      "/images/internal/Peugeot/peugeot-2008-3.jpg"
    ],
    mileage: 70000,
    model: 1399,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "مدرن‌ترین محصول ایکاپ با موتور قدرتمند ۱۶۳ اسب بخاری. شتاب اولیه بی‌رقیب در کلاس خود، گیربکس ۶ سرعته آیسین ژاپن و بدنه کاملاً بی رنگ. خودرو با وسواس زیاد نگهداری شده است.",
    hasGuarantee: "yes",
  },
  {
    id: 29,
    title: "هیوندای اکسنت",
    category: "Hyundai",
    price: 2600000000,
    imgSrc: [
      "/images/foreigner/Hyundai/accent-1.jpg",
      "/images/foreigner/Hyundai/accent-2.jpg",
      "/images/foreigner/Hyundai/accent-3.jpg"
    ],
    mileage: 85000,
    model: 2016,
    gearbox: "اتوماتیک",
    color: "مشکی",
    bodyStatus: "بی رنگ",
    descriptiion: "سدان جمع و جور و بسیار کم‌مصرف، عالی برای ترددهای روزانه. دارای مانیتور، دوربین دنده عقب و استارت دکمه‌ای. خودرو وارداتی بوده و از نظر کیفیت متریال با مدل‌های مونتاژی متفاوت است.",
    hasGuarantee: "yes",
  },
  {
    id: 30,
    title: "تیبا صندوق دار",
    category: "Saipa",
    price: 330000000,
    imgSrc: [
      "/images/internal/Saipa/tiba-sedan-1.jpg",
      "/images/internal/Saipa/tiba-sedan-2.jpg",
      "/images/internal/Saipa/tiba-sedan-3.jpg"
    ],
    mileage: 90000,
    model: 1398,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "رنگ دار",
    descriptiion: "ماشین بسیار خوش‌رکاب و فنی سالم. روکش صندلی‌ها تمیز، ضبط بلوتوث‌دار و لاستیک‌های جلو نو هستند. به دلیل رنگ‌دار بودن بدنه، قیمت را بسیار منصفانه گذاشتم تا سریع فروش برود.",
    hasGuarantee: "no",
  },
  {
    id: 31,
    title: "مرسدس S500",
    category: "Mercedes Benz",
    price: 21000000000,
    imgSrc: [
      "/images/foreigner/MercedesBenz/benz-s500-1.jpg",
      "/images/foreigner/MercedesBenz/benz-s500-2.jpg",
      "/images/foreigner/MercedesBenz/benz-s500-3.jpg"
    ],
    mileage: 130000,
    model: 2011,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "اوج مهندسی مرسدس بنز. خودروی تشریفاتی با امکانات بی‌پایان: یخچال، مانیتور پشت صندلی، سیستم دید در شب (Night Vision) و تنظیم ارتفاع. تجربه‌ای از لوکس بودن که در هیچ ماشین دیگری نخواهید یافت.",
    hasGuarantee: "yes",
  },
  {
    id: 32,
    title: "پژو 301",
    category: "Peugeot",
    price: 1500000000,
    imgSrc: [
      "/images/internal/Peugeot/peugeot-301-1.jpg",
      "/images/internal/Peugeot/peugeot-301-2.jpg",
      "/images/internal/Peugeot/peugeot-301-3.jpg"
    ],
    mileage: 60000,
    model: 1398,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "سدان وارداتی پژو با کیفیت ساخت بسیار بالا. سواری نرم و هندلینگ عالی در جاده، مجهز به سیستم‌های ایمنی روز اروپا. خودرو بسیار کم‌کارکرد بوده و تمام قطعات آن فابریک کارخانه است.",
    hasGuarantee: "yes",
  },
  {
    id: 33,
    title: "تویوتا CHR",
    category: "Toyota",
    price: 5200000000,
    imgSrc: [
      "/images/foreigner/Toyota/chr-1.jpg",
      "/images/foreigner/Toyota/chr-2.jpg",
      "/images/foreigner/Toyota/chr-3.jpg"
    ],
    mileage: 70000,
    model: 2018,
    gearbox: "اتوماتیک",
    color: "نقره ای",
    bodyStatus: "بی رنگ",
    descriptiion: "طراحی آینده‌نگرانه و فضایی که هر چشمی را خیره می‌کند. نسخه توربو تمام چرخ محرک (AWD)، با آپشن‌های کامل ایمنی از جمله رادار تشخیص عابر پیاده. ماشینی برای خاص‌پسندان با تکنولوژی ژاپنی.",
    hasGuarantee: "yes",
  },
  {
    id: 34,
    title: "بی ام و 730",
    category: "Bmw",
    price: 19500000000,
    imgSrc: [
      "/images/foreigner/Bmw/bmw-730-1.jpg",
      "/images/foreigner/Bmw/bmw-730-2.jpg",
      "/images/foreigner/Bmw/bmw-730-3.jpg"
    ],
    mileage: 90000,
    model: 2017,
    gearbox: "اتوماتیک",
    color: "مشکی",
    bodyStatus: "بی رنگ",
    descriptiion: "سدان پرچمدار سری ۷ با بدنه کربن کور (Carbon Core). مجهز به ریموت کنترل هوشمند، پارک خودکار و سیستم صوتی حرفه‌ای. خودرو در وضعیت کلکسیونی نگهداری شده و تمامی آپشن‌ها کاملاً سالم هستند.",
    hasGuarantee: "yes",
  },
  {
    id: 35,
    title: "شاهین G",
    category: "Saipa",
    price: 780000000,
    imgSrc: [
      "/images/internal/Saipa/shahin-g-1.jpg",
      "/images/internal/Saipa/shahin-g-2.jpg",
      "/images/internal/Saipa/shahin-g-3.jpg"
    ],
    mileage: 20000,
    model: 1402,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "شاهین تیپ G مجهز به سانروف و استارت دکمه‌ای. موتور توربوشارژ پرقدرت با گشتاور بالا، بدنه بدون قری و خط و خش. گارانتی فعال تا ۳ سال آینده و دارای کارت طلایی کامل سایپا.",
    hasGuarantee: "yes",
  },
  {
    id: 36,
    title: "هیوندای سوناتا",
    category: "Hyundai",
    price: 4300000000,
    imgSrc: [
      "/images/foreigner/Hyundai/sonata-1.jpg",
      "/images/foreigner/Hyundai/sonata-2.jpg",
      "/images/foreigner/Hyundai/sonata-3.jpg"
    ],
    mileage: 110000,
    model: 2016,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "سوناتا LF با طراحی با وقار و کلاسیک. مجهز به سقف پانوراما، سردکن و گرم‌کن صندلی‌ها و درایو مد (Drive Mode). خودرو خانگی بوده و تمامی قطعات مصرفی با نمونه‌های اصلی جنیون پارت تعویض شده است.",
    hasGuarantee: "yes",
  },
  {
    id: 37,
    title: "پژو 206 صندوق دار",
    category: "Peugeot",
    price: 690000000,
    imgSrc: [
      "/images/internal/Peugeot/peugeot-206sd-1.jpg",
      "/images/internal/Peugeot/peugeot-206sd-2.jpg",
      "/images/internal/Peugeot/peugeot-206sd-3.jpg"
    ],
    mileage: 120000,
    model: 1396,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "رنگ دار",
    descriptiion: "۲۰۶ اس‌دی V8 با موتور TU5 بسیار پرقدرت. دارای سنسور دنده عقب، ضبط و باندهای باکیفیت و روکش صندلی مخمل. از نظر فنی بسیار به آن رسیدگی شده و آماده مسافرت‌های طولانی است.",
    hasGuarantee: "no",
  },
  {
    id: 38,
    title: "تویوتا پریوس",
    category: "Toyota",
    price: 4700000000,
    imgSrc: [
      "/images/foreigner/Toyota/prius-1.jpg",
      "/images/foreigner/Toyota/prius-2.jpg",
      "/images/foreigner/Toyota/prius-3.jpg"
    ],
    mileage: 95000,
    model: 2017,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "قهرمان مصرف سوخت و دوست‌دار محیط زیست. سیستم هیبریدی کاملاً سالم به شرط استعلام نمایندگی ایرتویا. کابین بسیار مدرن و سواری بی‌صدا، انتخابی هوشمندانه برای کسانی که به دنبال تکنولوژی هستند.",
    hasGuarantee: "yes",
  },
  {
    id: 39,
    title: "بی ام و Z4",
    category: "Bmw",
    price: 12500000000,
    imgSrc: [
      "/images/foreigner/Bmw/bmw-z4-1.jpg",
      "/images/foreigner/Bmw/bmw-z4-2.jpg",
      "/images/foreigner/Bmw/bmw-z4-3.jpg"
    ],
    mileage: 60000,
    model: 2014,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "رودستر اسپرت با سقف کروک برقی. رنگ سفید استثنایی و کیت M فابریک. صدای اگزوز گوش‌نواز و شتاب اولیه فوق‌العاده؛ این خودرو مخصوص لذت بردن از رانندگی در جاده‌های کوهستانی و ساحلی است.",
    hasGuarantee: "yes",
  },
  {
    id: 40,
    title: "مرسدس GLA",
    category: "Mercedes Benz",
    price: 9300000000,
    imgSrc: [
      "/images/foreigner/MercedesBenz/benz-gla-1.jpg",
      "/images/foreigner/MercedesBenz/benz-gla-2.jpg",
      "/images/foreigner/MercedesBenz/benz-gla-3.jpg"
    ],
    mileage: 85000,
    model: 2018,
    gearbox: "اتوماتیک",
    color: "نقره ای تیتانیوم",
    bodyStatus: "بی رنگ",
    descriptiion: "کراس‌اوور لوکس و جمع‌وجور مرسدس بنز با سیستم 4Matic. هندلینگ در حد سدان و فضای کاربردی یک شاسی‌بلند. مجهز به رادارهای پیشرفته و سیستم صوتی باکیفیت، بدنه بدون حتی یک خط و خش ریز.",
    hasGuarantee: "yes",
  },
  {
    id: 41,
    title: "پراید وانت",
    category: "Saipa",
    price: 310000000,
    imgSrc: [
      "/images/internal/Saipa/pride-vanet-1.jpg",
      "/images/internal/Saipa/pride-vanet-2.jpg",
      "/images/internal/Saipa/pride-vanet-3.jpg"
    ],
    mileage: 140000,
    model: 1397,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "رنگ دار",
    descriptiion: "بهترین گزینه برای پخش کالا و کسب درآمد. فنربندی تقویت شده برای باربری بهتر، کفی لاینر نو نصب شده و موتور بدون قطره‌ای روغن‌سوزی. با این قیمت، نقدترین سرمایه برای شروع یک کار پردرآمد است.",
    hasGuarantee: "no",
  },
  {
    id: 42,
    title: "پژو RD",
    category: "Peugeot",
    price: 350000000,
    imgSrc: [
      "/images/internal/Peugeot/peugeot-rd-1.jpg",
      "/images/internal/Peugeot/peugeot-rd-2.jpg",
      "/images/internal/Peugeot/peugeot-rd-3.jpg"
    ],
    mileage: 200000,
    model: 1388,
    gearbox: "دنده دستی",
    color: "سبز",
    bodyStatus: "رنگ دار",
    descriptiion: "خودرویی با بدنه محکم ۴۰۵ و موتور پیکان، بسیار ارزان و در عین حال جادار. دیفرانسیل بدون صدا، کولر و بخاری فعال. مناسب برای کسانی که با بودجه کم به دنبال یک ماشین خانوادگی و مقاوم هستند.",
    hasGuarantee: "no",
  },
  {
    id: 43,
    title: "هیوندای i20",
    category: "Hyundai",
    price: 2400000000,
    imgSrc: [
      "/images/foreigner/Hyundai/i20-1.jpg",
      "/images/foreigner/Hyundai/i20-2.jpg",
      "/images/foreigner/Hyundai/i20-3.jpg"
    ],
    mileage: 70000,
    model: 2016,
    gearbox: "اتوماتیک",
    color: "قهوه ای",
    bodyStatus: "بی رنگ",
    descriptiion: "هاچ‌بک باکیفیت و شیک، محبوب خانم‌ها و جوانان. رنگ آبی متالیک بسیار تمیز، دارای مانیتور فابریک و آینه‌های برقی تاشو. ابعاد کوچک این ماشین پارک کردن در فضاهای تنگ شهری را بسیار آسان می‌کند.",
    hasGuarantee: "yes",
  },
  {
    id: 44,
    title: "تویوتا هایلوکس",
    category: "Toyota",
    price: 7800000000,
    imgSrc: [
      "/images/foreigner/Toyota/hilux-1.jpg",
      "/images/foreigner/Toyota/hilux-2.jpg",
      "/images/foreigner/Toyota/hilux-3.jpg"
    ],
    mileage: 160000,
    model: 2014,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "پادشاه آفرود و سخت‌کوشی. هایلوکس دو کابین بلند با سیستم تعلیق بسیار مستحکم. خودرو به خوبی نگهداری شده و هرگز تحت فشارهای غیرمتعارف نبوده است. تمام قطعات مکانیکی در سلامت ۱۰۰ درصدی هستند.",
    hasGuarantee: "yes",
  },
  {
    id: 45,
    title: "بی ام و X6",
    category: "Bmw",
    price: 17500000000,
    imgSrc: [
      "/images/foreigner/Bmw/bmw-x6-1.jpg",
      "/images/foreigner/Bmw/bmw-x6-2.jpg",
      "/images/foreigner/Bmw/bmw-x6-3.jpg"
    ],
    mileage: 105000,
    model: 2016,
    gearbox: "اتوماتیک",
    color: "مشکی",
    bodyStatus: "بی رنگ",
    descriptiion: "ترکیب جسورانه شاسی‌بلند و کوپه. ابهت بی‌نظیر در جاده به همراه قدرت موتور ویران‌گر. خودرو فول آپشن با کیت M، رینگ‌های ۲۰ اینچی و مجهز به مکش درب‌ها. بدون هیچ‌گونه خطا در سیستم‌های الکترونیکی.",
    hasGuarantee: "yes",
  },
  {
    id: 46,
    title: "مرسدس CLS",
    category: "Mercedes Benz",
    price: 14200000000,
    imgSrc: [
      "/images/foreigner/MercedesBenz/benz-cls-1.jpg",
      "/images/foreigner/MercedesBenz/benz-cls-2.jpg",
      "/images/foreigner/MercedesBenz/benz-cls-3.jpg"
    ],
    mileage: 99000,
    model: 2015,
    gearbox: "اتوماتیک",
    color: "مشکی",
    bodyStatus: "بی رنگ",
    descriptiion: "زیباترین سدان کوپه جهان با طراحی ایرودینامیک منحصر‌به‌فرد. سیستم صوتی پیشرفته، تنظیمات صندلی در تمام جهات و سقف جیر. خودرو در بهترین وضعیت کلکسیونی بوده و آماده بازدیدی دقیق توسط کارشناس شماست.",
    hasGuarantee: "yes",
  },
  {
    id: 47,
    title: "رانا پلاس",
    category: "Peugeot",
    price: 520000000,
    imgSrc: [
      "/images/internal/Peugeot/runna-plus-1.jpg",
      "/images/internal/Peugeot/runna-plus-2.jpg",
      "/images/internal/Peugeot/runna-plus-3.jpg"
    ],
    mileage: 35000,
    model: 1401,
    gearbox: "دنده دستی",
    color: "نوک مدادی",
    bodyStatus: "بی رنگ",
    descriptiion: "رانا پلاس با گیربکس جدید و فرمان برقی. خودرو مشابه صفر کیلومتر، دارای کروز کنترل و دی‌لایت. رنگ نوک مدادی متالیک بسیار شیک که خط و خش را نشان نمی‌دهد. سرویس‌های اولیه با دقت بالا انجام شده است.",
    hasGuarantee: "yes",
  },
  {
    id: 48,
    title: "پژو 405 SLX",
    category: "Peugeot",
    price: 560000000,
    imgSrc: [
      "/images/internal/Peugeot/peugeot-405slx-1.jpg",
      "/images/internal/Peugeot/peugeot-405slx-2.jpg",
      "/images/internal/Peugeot/peugeot-405slx-3.jpg"
    ],
    mileage: 145000,
    model: 1396,
    gearbox: "دنده دستی",
    color: "سفید",
    bodyStatus: "رنگ دار",
    descriptiion: "۴۰۵ موتور TU5 با چراغ‌های جدید و آینه‌های برقی. خودرو بسیار کم‌مصرف و پرقدرت، داخل اتاق بسیار تمیز و بدون سر و صدا. تمام لوازم مصرفی از جمله تسمه تایم و باتری به تازگی تعویض شده‌اند.",
    hasGuarantee: "no",
  },
  {
    id: 49,
    title: "هیوندای وراکروز",
    category: "Hyundai",
    price: 6200000000,
    imgSrc: [
      "/images/foreigner/Hyundai/veracruz-1.jpg",
      "/images/foreigner/Hyundai/veracruz-2.jpg",
      "/images/foreigner/Hyundai/veracruz-3.jpg"
    ],
    mileage: 150000,
    model: 2013,
    gearbox: "اتوماتیک",
    color: "مشکی",
    bodyStatus: "بی رنگ",
    descriptiion: "بزرگترین و جادارترین شاسی‌بلند هیوندای با موتور ۳۸۰۰ سی‌سی. سواری فوق‌العاده نرم و جاداری بی‌نظیر برای ۷ نفر. سیستم صوتی اینفینیتی، صندوق عقب برقی و سیستم پایداری هوشمند از ویژگی‌های این غول کره‌ای است.",
    hasGuarantee: "yes",
  },
  {
    id: 50,
    title: "تویوتا یاریس",
    category: "Toyota",
    price: 2100000000,
    imgSrc: [
      "/images/foreigner/Toyota/yaris-1.jpg",
      "/images/foreigner/Toyota/yaris-2.jpg",
      "/images/foreigner/Toyota/yaris-3.jpg"
    ],
    mileage: 80000,
    model: 2015,
    gearbox: "اتوماتیک",
    color: "سفید",
    bodyStatus: "بی رنگ",
    descriptiion: "سدان شهری تویوتا با استهلاک نزدیک به صفر. ماشینی بسیار جمع و جور و خوش‌فرمان برای ترافیک کلان‌شهرها. کارکرد واقعی و بدنه بدون رنگ، تودوزی داخلی مشابه روز اول و بسیار تمیز نگهداری شده است.",
    hasGuarantee: "yes",
  }
];